### ISSUE TITLE
Minifier doesn't provide stats for bundle-visualizer

### ISSUE THREAD

**Issue by oleg-rdk** [abernix/minifier-js#1]
Thanks for upgrading Meteor to v1.5, when using bundle-visualizer it throws next error:

```
bundle-visualizer: Couldn't load stats for visualization.
Are you using standard-minifier-js >= 2.1.0 as the minifier?
```

Is there any ability to pull changes from default packages to be able to see bundle visualization?

Thanks in advance!

**Comment by abernix** [comment]
`bundle-visualizer` should work in the latest version! :smile:
